name: rootasjey
description: My personal website.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.20.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  adaptive_theme: 2.0.0
  animations: 2.0.0
  auto_route:  1.0.2
  cloud_firestore: 1.0.1
  cloud_functions: 1.0.0
  cross_local_storage: 2.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  data_connection_checker: 0.3.4
  easy_localization: 3.0.0
  file_saver: 0.0.6
  firebase_auth: 1.0.1
  firebase_core: 1.0.1
  firebase_analytics: 7.1.1
  flash: 1.5.0
  flushbar: 1.10.4
  flutter:
    sdk: flutter
  flutter_html: 2.0.0-nullsafety.0
  flutter_mobx: 2.0.0-nullsafety.3
  flutter_sticky_header: 0.5.0
  flutter_syntax_view: 4.0.0
  font_awesome_flutter: 9.0.0
  github: 8.0.1
  google_fonts: 2.0.0
  jiffy: 4.0.0
  line_awesome_flutter: 1.0.1
  like_button: 2.0.2
  logger: 1.0.0
  markdown: 4.0.0
  mobx: 2.0.0-nullsafety.5
  screenshot: 0.3.0
  share: 2.0.1
  simple_animations: 3.0.3
  sticky_headers: 0.2.0
  supercharged: 2.0.0
  unicons: 1.0.2
  url_launcher: 6.0.2
  url_strategy: 0.2.0
  verbal_expressions: 0.4.0

dev_dependencies:
  auto_route_generator: 1.0.2
  build_runner:
  flutter_launcher_icons: 0.9.0
  flutter_rename_app:
    git: https://github.com/rootasjey/flutter_rename_app.git
  flutter_test:
    sdk: flutter
  mobx_codegen: 2.0.0-nullsafety.2

flutter_icons:
  android: "launcher_icon"
  ios: "launcher_icon"
  image_path_android: "assets/images/app-launch-icon-android.png"
  image_path_ios: "assets/images/app-launch-icon-ios.jpg"

flutter_rename_app:
  application_name: rootasjey
  dart_package_name: rootasjey
  application_id: dev.android.rootasjey
  bundle_id: dev.ios.rootasjey
  android_package_name: dev.android.rootasjey

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/app_icon/32.png
    - assets/images/app_icon/64.png
    - assets/images/app_icon/128.png
    - assets/images/app_icon/256.png
    - assets/images/app_icon/512.png
    - assets/images/app_icon/1024.png
    - assets/images/app_icon/animation.gif
    - assets/images/comet-logo-wide.jpg
    - assets/images/figstyle.png
    - assets/images/firebase.png
    - assets/images/flutter.png
    - assets/images/jeje.jpg
    - assets/images/malt-logo-white.png
    - assets/images/relines.png
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
